matrix:
  include:
    - name: "Backend Build"
      language: java
      jdk: oraclejdk11
      install: true
      script:
          - cd euphoria-service/ && mvn clean package -B -V

    - name: "Frontend Build"
      language: node_js
      node_js: 4
      install:
        - cd euphoria-frontend/ && npm install
      script:
        - cd euphoria-frontend/ && npm test
      cache:
        directories:
          - "node_modules"

notifications:
  email: false
