package edu.cooper.ece366.euphoria;

public enum Location {
    NEWYORK, LONDON, HONGKONG, BERLIN, BEIJING, WASHINGTON
}

public enum EducationLevel {
    NOHIGHSCHOOL, HIGHSCHOOL, GED, SOMECOLLEGE, ASSOCIATES, BACHELORS, MASTERS, PHD, MD, JD
}

public enum Industry {
    EDUCATION, ENERGY, FINANCE, FOOD, HEALTHCARE, INSURANCE, MEDIA, RETAIL, SERVICES, TECHNOLOGY, TRANSPORT, UTILITIES
}
